services:
  rag-app:
    build: .
    
    container_name: secure-rag
    
    env_file:
      - .env
    
    volumes:
      - ./${DATA_FOLDER:-data}:/app/${DATA_FOLDER:-data}
    
    stdin_open: true 
    tty: true