services:
  hybrid-rag-app:
    build: .
    
    container_name: hybrid-rag
    
    env_file:
      - .env
    
    # Maps local data folder to container data folder
    volumes:
      - ./${DATA_FOLDER:-data}:/app/${DATA_FOLDER:-data}

    ports:
      - "8501:8501"
    
    stdin_open: true 
    tty: true